In [1]:
import pandas as pd 
from sklearn.model_selection import train_test_split

In [4]:
df = pd.read_csv("C:\\Users\\rajan\\Downloads\\spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
df.isnull().sum()

Category    0
Message     0
dtype: int64

In [3]:
df['label'] = df.Category.apply(lambda x : 1 if x == 'spam' else 0)
df.head()

Category                                            Message  label
0      ham  Go until jurong point, crazy.. Available only ...      0
1      ham                      Ok lar... Joking wif u oni...      0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...      1
3      ham  U dun say so early hor... U c already then say...      0
4      ham  Nah I don't think he goes to usf, he lives aro...      0

In [4]:
df.drop('Category' , axis = 1  , inplace = True)

In [5]:
df.head()

Message  label
0  Go until jurong point, crazy.. Available only ...      0
1                      Ok lar... Joking wif u oni...      0
2  Free entry in 2 a wkly comp to win FA Cup fina...      1
3  U dun say so early hor... U c already then say...      0
4  Nah I don't think he goes to usf, he lives aro...      0

In [6]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(df.Message , df.label , test_size=0.25)

In [9]:
x_train.values

array(["(You didn't hear it from me)", "I'm awake oh. What's up.",
       "Whenevr ur sad, Whenevr ur gray, Remembr im here 2 listn 2 watevr u wanna say, Jus walk wid me a little while,&amp; I promise I'll bring back ur smile.:-)",
       ..., 'K do I need a login or anything',
       'LOL ... Have you made plans for new years?',
       'Huh means computational science... Y they like dat one push here n there...'],
      dtype=object)

In [14]:
x_train

5038                         (You didn't hear it from me)
4561                             I'm awake oh. What's up.
1316    Whenevr ur sad, Whenevr ur gray, Remembr im he...
1827    Dude. What's up. How Teresa. Hope you have bee...
3570                      She's fine. Sends her greetings
                              ...                        
123     Todays Voda numbers ending 7548 are selected t...
1438    Wat so late still early mah. Or we juz go 4 di...
1136                      K do I need a login or anything
449            LOL ... Have you made plans for new years?
2416    Huh means computational science... Y they like...
Name: Message, Length: 4179, dtype: object

In [15]:
type(x_train.values) , type(x_train)

(numpy.ndarray, pandas.core.series.Series)

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
x_train_count = v.fit_transform(x_train.values)

In [13]:
x_train_count.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [17]:
print(v.get_feature_names()) # it gives all the unique words present in the x_train

['00', '000', '000pes', '008704050406', '0089', '0121', '01223585236', '01223585334', '0125698789', '02', '0207', '02072069400', '02073162414', '02085076972', '021', '03', '04', '0430', '05', '050703', '0578', '06', '07', '07008009200', '07090298926', '07099833605', '07123456789', '07732584351', '07734396839', '07742676969', '0776xxxxxxx', '07781482378', '077xxx', '078', '07801543489', '07808', '07815296484', '07821230901', '078498', '07880867867', '0789xxxxxxx', '07946746291', '0796xxxxxx', '07973788240', '07xxxxxxxxx', '08', '0800', '08000407165', '08000776320', '08000839402', '08000930705', '08000938767', '08001950382', '08002888812', '08002986030', '08002986906', '08002988890', '08006344447', '0808', '08081263000', '0825', '083', '0844', '08448350055', '0845', '08450542832', '08452810071', '08452810073', '08452810075over18', '0870', '08700469649', '08700621170150p', '08701237397', '08701417012', '08701417012150p', '0870141701216', '087016248', '08701752560', '0870241182716', '08702

C:\Users\rajan\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [18]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(x_train_count, y_train)

MultinomialNB()

In [22]:
emails = [
    'Hi, Rajan how are you. I hope you are doing well although it is hard time for you.',
    'Hurry up  , there is 50% discount offer on the Machine learning course , Dont miss this reward'
]

In [23]:
emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

In [24]:
x_test_count = v.transform(x_test)
model.score(x_test_count , y_test)

0.9849246231155779

In [25]:
from sklearn.pipeline import Pipeline
clf = Pipeline([
    ('vectorizer' , CountVectorizer()),
    ('nb', MultinomialNB())
    
])


In [26]:
clf.fit(x_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [27]:
clf.score(x_test , y_test)

0.9849246231155779

In [28]:
clf.predict(emails)

array([0, 1], dtype=int64)

5038                         (You didn't hear it from me)
4561                             I'm awake oh. What's up.
1316    Whenevr ur sad, Whenevr ur gray, Remembr im he...
1827    Dude. What's up. How Teresa. Hope you have bee...
3570                      She's fine. Sends her greetings
                              ...                        
123     Todays Voda numbers ending 7548 are selected t...
1438    Wat so late still early mah. Or we juz go 4 di...
1136                      K do I need a login or anything
449            LOL ... Have you made plans for new years?
2416    Huh means computational science... Y they like...
Name: Message, Length: 4179, dtype: object