In [1]:
import pandas as pd 
import numpy as np 
from sklearn.linear_model import LogisticRegression


In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/codebasics/py/master/ML/18_PCA/Exercise/heart.csv")
print(df.shape)
df.head(10)

(918, 12)


Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140          289          0     Normal    172   
1   49   F           NAP        160          180          0     Normal    156   
2   37   M           ATA        130          283          0         ST     98   
3   48   F           ASY        138          214          0     Normal    108   
4   54   M           NAP        150          195          0     Normal    122   
5   39   M           NAP        120          339          0     Normal    170   
6   45   F           ATA        130          237          0     Normal    170   
7   54   M           ATA        110          208          0     Normal    142   
8   37   M           ASY        140          207          0     Normal    130   
9   48   F           ATA        120          284          0     Normal    120   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              N      0.0       Up             0  
1              N      1.0     Flat             1  
2              N      0.0       Up             0  
3              Y      1.5     Flat             1  
4              N      0.0       Up             0  
5              N      0.0       Up             0  
6              N      0.0       Up             0  
7              N      0.0       Up             0  
8              Y      1.5     Flat             1  
9              N      0.0       Up             0

In [49]:
df['RestingECG'].unique()

array(['Normal', 'ST', 'LVH'], dtype=object)

In [50]:
df2  = df[['Sex' , 'ChestPainType' , 'RestingECG','ST_Slope', 'ExerciseAngina']]
df2 = pd.get_dummies(df2 , drop_first=True)
df2

Sex_M  ChestPainType_ATA  ChestPainType_NAP  ChestPainType_TA  \
0        1                  1                  0                 0   
1        0                  0                  1                 0   
2        1                  1                  0                 0   
3        0                  0                  0                 0   
4        1                  0                  1                 0   
..     ...                ...                ...               ...   
913      1                  0                  0                 1   
914      1                  0                  0                 0   
915      1                  0                  0                 0   
916      0                  1                  0                 0   
917      1                  0                  1                 0   

     RestingECG_Normal  RestingECG_ST  ST_Slope_Flat  ST_Slope_Up  \
0                    1              0              0            1   
1                    1              0              1            0   
2                    0              1              0            1   
3                    1              0              1            0   
4                    1              0              0            1   
..                 ...            ...            ...          ...   
913                  1              0              1            0   
914                  1              0              1            0   
915                  1              0              1            0   
916                  0              0              1            0   
917                  1              0              0            1   

     ExerciseAngina_Y  
0                   0  
1                   0  
2                   0  
3                   1  
4                   0  
..                ...  
913                 0  
914                 0  
915                 1  
916                 0  
917                 0  

[918 rows x 9 columns]

In [51]:
df.drop(['Sex' , 'ChestPainType' , 'RestingECG','ST_Slope', 'ExerciseAngina'] , axis = 1, inplace = True)

In [52]:

df.head()

Age  RestingBP  Cholesterol  FastingBS  MaxHR  Oldpeak  HeartDisease
0   40        140          289          0    172      0.0             0
1   49        160          180          0    156      1.0             1
2   37        130          283          0     98      0.0             0
3   48        138          214          0    108      1.5             1
4   54        150          195          0    122      0.0             0

In [53]:
df = pd.concat([df, df2] , axis = 1 )
df.head()

Age  RestingBP  Cholesterol  FastingBS  MaxHR  Oldpeak  HeartDisease  \
0   40        140          289          0    172      0.0             0   
1   49        160          180          0    156      1.0             1   
2   37        130          283          0     98      0.0             0   
3   48        138          214          0    108      1.5             1   
4   54        150          195          0    122      0.0             0   

   Sex_M  ChestPainType_ATA  ChestPainType_NAP  ChestPainType_TA  \
0      1                  1                  0                 0   
1      0                  0                  1                 0   
2      1                  1                  0                 0   
3      0                  0                  0                 0   
4      1                  0                  1                 0   

   RestingECG_Normal  RestingECG_ST  ST_Slope_Flat  ST_Slope_Up  \
0                  1              0              0            1   
1                  1              0              1            0   
2                  0              1              0            1   
3                  1              0              1            0   
4                  1              0              0            1   

   ExerciseAngina_Y  
0                 0  
1                 0  
2                 0  
3                 1  
4                 0

In [54]:
target = df['HeartDisease']
df.drop('HeartDisease' , axis = 1 , inplace = True)
df.head()

Age  RestingBP  Cholesterol  FastingBS  MaxHR  Oldpeak  Sex_M  \
0   40        140          289          0    172      0.0      1   
1   49        160          180          0    156      1.0      0   
2   37        130          283          0     98      0.0      1   
3   48        138          214          0    108      1.5      0   
4   54        150          195          0    122      0.0      1   

   ChestPainType_ATA  ChestPainType_NAP  ChestPainType_TA  RestingECG_Normal  \
0                  1                  0                 0                  1   
1                  0                  1                 0                  1   
2                  1                  0                 0                  0   
3                  0                  0                 0                  1   
4                  0                  1                 0                  1   

   RestingECG_ST  ST_Slope_Flat  ST_Slope_Up  ExerciseAngina_Y  
0              0              0            1                 0  
1              0              1            0                 0  
2              1              0            1                 0  
3              0              1            0                 1  
4              0              0            1                 0

In [55]:
x = df
y = target

In [56]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_scale = scaler.fit_transform(x)
x_scale


array([[-1.4331398 ,  0.41090889,  0.82507026, ..., -1.00218103,
         1.15067399, -0.8235563 ],
       [-0.47848359,  1.49175234, -0.17196105, ...,  0.99782372,
        -0.86905588, -0.8235563 ],
       [-1.75135854, -0.12951283,  0.7701878 , ..., -1.00218103,
         1.15067399, -0.8235563 ],
       ...,
       [ 0.37009972, -0.12951283, -0.62016778, ...,  0.99782372,
        -0.86905588,  1.21424608],
       [ 0.37009972, -0.12951283,  0.34027522, ...,  0.99782372,
        -0.86905588, -0.8235563 ],
       [-1.64528563,  0.30282455, -0.21769643, ..., -1.00218103,
         1.15067399, -0.8235563 ]])

In [57]:
from sklearn.model_selection import train_test_split
x_train , x_test  , y_train , y_test = train_test_split(x_scale, y , test_size=0.25  , random_state=45)

In [58]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [59]:
def PrintScore(x_train , x_test , y_train , y_test):
    logreg = LogisticRegression(max_iter=1000 , solver ='liblinear' , multi_class='auto')
    logreg.fit(x_train , y_train)
    log_score = logreg.score(x_test , y_test)
    
    svm = SVC(kernel = 'rbf' , gamma= 'auto' , C =20)
    svm.fit(x_train , y_train)
    svm_score = svm.score(x_test , y_test)
    
    randforest = RandomForestClassifier()
    randforest.fit(x_train , y_train)
    rand_score = randforest.score(x_test , y_test)
    print("LogisiticRegression_score: {} , svm_score: {}  , randomforest_score : {}".format(log_score , svm_score , rand_score))

In [60]:
PrintScore(x_train , x_test  , y_train , y_test )

LogisiticRegression_score: 0.8695652173913043 , svm_score: 0.8391304347826087  , randomforest_score : 0.8652173913043478


In [61]:
x_train.shape , x_scale.shape , x.shape , y.shape

((688, 15), (918, 15), (918, 15), (918,))

In [62]:
from sklearn.decomposition import PCA
pca1 = PCA(0.90)
pca2 = PCA(n_components=10)
x_pca1  = pca1.fit_transform(x_scale)
x_pca2  = pca2.fit_transform(x_scale)
x_pca1.shape , x_pca2.shape

((918, 11), (918, 10))

In [64]:
x_pca1

array([[ 3.1402362 , -0.42350279, -0.64563841, ..., -0.90909348,
        -0.08335011,  0.28938107],
       [ 0.23236559, -1.09015917, -0.77834553, ..., -0.94692068,
         1.40012916,  0.97167145],
       [ 1.65293842,  2.15351134, -0.30496793, ..., -1.15415068,
        -0.12727282, -0.54497203],
       ...,
       [-1.74810152, -1.4884599 ,  0.33744274, ..., -0.06964515,
         0.25658839,  0.04853522],
       [ 1.10315428,  0.2074868 , -1.7572611 , ..., -0.31440412,
        -0.53709022,  1.17486636],
       [ 2.52724324, -0.47874292,  0.95291862, ..., -0.91670795,
         0.82703874,  0.12410967]])

In [65]:
x_pca2

array([[ 3.1402362 , -0.42350279, -0.64563841, ..., -0.982055  ,
        -0.90909348, -0.08335011],
       [ 0.23236559, -1.09015917, -0.77834553, ..., -0.3661935 ,
        -0.94692068,  1.40012916],
       [ 1.65293842,  2.15351134, -0.30496793, ...,  0.55981637,
        -1.15415068, -0.12727282],
       ...,
       [-1.74810152, -1.4884599 ,  0.33744274, ...,  0.68136467,
        -0.06964515,  0.25658839],
       [ 1.10315428,  0.2074868 , -1.7572611 , ..., -0.13524783,
        -0.31440412, -0.53709022],
       [ 2.52724324, -0.47874292,  0.95291862, ..., -0.75891039,
        -0.91670795,  0.82703874]])

In [66]:
from sklearn.model_selection import train_test_split
x_train , x_test  , y_train , y_test = train_test_split(x_pca1, y , test_size=0.25  , random_state=45)

In [67]:
PrintScore(x_train , x_test  , y_train , y_test )

LogisiticRegression_score: 0.8565217391304348 , svm_score: 0.808695652173913  , randomforest_score : 0.8565217391304348


In [68]:
from sklearn.model_selection import train_test_split
x_train , x_test  , y_train , y_test = train_test_split(x_pca2, y , test_size=0.25  , random_state=45)

In [69]:
PrintScore(x_train , x_test  , y_train , y_test )

LogisiticRegression_score: 0.8521739130434782 , svm_score: 0.8173913043478261  , randomforest_score : 0.8521739130434782
